### ISSUE TITLE
Mailing list down

### ISSUE THREAD

**Issue by SpareSimian** [The-McGrail-Foundation/MIMEDefang#25]
I sent a question to the mailing list on Feb. 26 and didn't see it appear on the list. Is that list dead? Is there a new place for operational questions?

**Comment by bigio** [comment]
On 3/3/21 9:43 PM, SpareSimian wrote:
> I sent a question to the mailing list on Feb. 26 and didn't see it appear on the list. Is that list dead? Is there a new place for operational questions?
> 

Could you try to resend the email to the mailing list ? We will take a look at the ml server.

 Thanks
  Giovanni

**Comment by SpareSimian** [comment]
Subject: Backscatter for receive-only role addresses

I'm able to log in to the list member management page and see my list settings.

I'm seeing this, even on an immediate retry. (I think Comcast fails to retry when it gets the 451 error so I have to send again manually from my Sent folder.) 

Reporting-MTA: dns; resqmta-ch2-09v.sys.comcast.net [69.252.207.41]
Received-From-MTA: dns; resomta-ch2-09v.sys.comcast.net [69.252.207.105]
Arrival-Date: Thu, 04 Mar 2021 19:18:52 +0000


Final-recipient: rfc822; mimedefang@lists.roaringpenguin.com
Diagnostic-Code: smtp; 451 4.3.0 <shiva@sewingwitch.com>... First-time sender tempfailed as anti-spam measure; please try again

Last-attempt-Date: Thu, 04 Mar 2021 19:19:01 +0000

**Comment by bigio** [comment]
Mailing list is now running at mimedefang@lists.mimedefang.org
