### ISSUE TITLE
Test header_timezone_works fails

### ISSUE THREAD

**Issue by a16bitsysop** [The-McGrail-Foundation/MIMEDefang#43]
I am trying to compile and run tests on alpine Linux edge branch with 2.85 release candidate, and get the following error when `make test` is run. Is it expecting system timezone to be `America/Regina`?

```
prove -It/lib --recurse t/unit
t/unit/dates.t .... 1/5
#   Failed test 'Got header timezone for TZ=America/Regina'
#   at t/unit/dates.t line 18.
#   (in MIMEDefang::Unit::dates->header_timezone_works)
#          got: '+0000'
#     expected: '-0600'
# Looks like you failed 1 test of 5.
t/unit/dates.t .... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests
t/unit/headers.t .. ok
t/unit/relay.t .... ok
t/unit/sender.t ... ok

Test Summary Report
-------------------
t/unit/dates.t  (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  3
  Non-zero exit status: 1
Files=4, Tests=51,  4 wallclock secs ( 0.13 usr  0.03 sys +  2.88 cusr  0.69 csys =  3.73 CPU)
Result: FAIL
```

**Comment by bigio** [comment]
America/Regina is a valid timezone and is present on /usr/share/zoneinfo on both Linux Fedora 34, CentOS7/8 and OpenBSD.
It has been chosen because it is one of the few timezone that doesn't observe DST and doesn't change during the year.
Is the file /usr/share/zoneinfo/America/Regina missing from Alpine Linux ?

**Comment by a16bitsysop** [comment]
No it didn’t exist as I was building inside a Docker container, it passed after I installed tzdata.  Thanks

**Comment by a16bitsysop** [comment]
Does that mean timezone data is a run dependency or a test dependency?

**Comment by bigio** [comment]
timezone data is a run and test dependency, it's used internally by Perl to check if Date: headers are correct and by unit tests.

**Comment by a16bitsysop** [comment]
Okay will add as a run dependency, it isn’t a dependency in mimedefang.spec

but perl-IO-stringy is, even though it isn’t tested for and tests pass without it.

**Comment by bigio** [comment]
mimedefang.spec file is a RedHat specific file and it's still stuck at 2.84.
perl-IO-stringy is actually not needed (I will fix is asap), tzdata package is not listed because it's a Perl dependency on RH based distros afaik.

**Comment by a16bitsysop** [comment]
Yes I know mimedefang.spec is RedHat specific, but I couldn’t see dependency info anywhere else.
tzdata isn’t a Perl dependency on alpine, it’s only actually required by 16 packages:
https://pkgs.alpinelinux.org/package/edge/main/x86_64/tzdata

the only Perl one being:
perl-posix-strftime-compiler

**Comment by bigio** [comment]
I added some more info to README file with commit 27277ecb4656727aa1be79f210399e2a25c3fef6

**Comment by a16bitsysop** [comment]
Thanks, there is also README.md that is almost empty.  Which GitHub displays, wouldn’t it be better to change README to README.md
