### ISSUE TITLE
Codespell report for "MIMEDefang" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [The-McGrail-Foundation/MIMEDefang#46]
A little bit nitpicking:

The FOSS server [fossies.org](https://fossies.org) - supporting also the [MIMEDefang](https://fossies.org/mimedefang) project - offers among others a feature named "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have just created for testing purposes such a [codespell](https://github.com/codespell-project/codespell) based analysis for the new and long-awaited "MIMEDefang" release 2.8.5:

 &nbsp;https://fossies.org/linux/misc/mimedefang/codespell.html

That version-independent (not linked) URL should redirect always to the last report (if available), so currently to

 &nbsp;https://fossies.org/linux/misc/mimedefang-2.85.tar.gz/codespell.html

By the way, the context type of the spelling errors and typos are marked by a single character (within the sortable column "T"): The less interesting, probably not user visible ones (in "comments") are greyed, while the probably more interesting ones are black-colored. If JavaScript is enabled all table columns are sortable.

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can force a new improved check if applicable.

Just for information there are also three supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/misc/mimedefang/codespell_conf.html), all obvious [false positives](https://fossies.org/linux/misc/mimedefang/codespell_fps.html) and an [misspelling history](https://fossies.org/linux/misc/mimedefang/codespell_hist.html) (log).

Perhaps more meaningful may be a similar and continuously updated report for the "MIMEDefang GitHub "master" version which could be generated on request within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines:

 &nbsp;https://fossies.org/linux/test/mimedefang-master.tar.gz/codespell.html

That version independent URL hopefully always redirects to the report for the latest "master" version identified by the short GitHub commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The refresh rate is currently half-hourly.

Although the correction of misspellings and typos has probably not a top priority, I hope that the report can nevertheless be a little bit useful.

Off-topic small remarks: In the new release the README file was replaced by a README.md file. Since the textual README file was already a little bit formatted like a Markdown file the according HTML rendering works reasonably but not very well (especially since lines with "--" are handled as an alternative syntax for heading level 2; see e.g. `"You must be using Sendmail 8.12.x or 8.13.x"`). Additionally, since the item `"4. MIME-BASE64 NOTE"` was removed the line `"5. INSTALLATION"` must be now probably numbered `"4. INSTALLATION"`. And in the list before the item `"4) Sendmail 8.12.x, 8.13.x or Postfix.  Get the latest version."` has the same number as the item before.

**Comment by bigio** [comment]
Spelling errors fixed on master, thanks for your great service.
