### ISSUE TITLE
Use Digest::SHA instead of Digest::SHA1?

### ISSUE THREAD

**Issue by robert-scheck** [The-McGrail-Foundation/MIMEDefang#53]
As of writing, `gen-ip-validator.pl`, `mimedefang.pl`/`mimedefang.pl.in` are using `Digest::SHA1`, but I would like suggest a switch to `Digest::SHA`, because: `Digest::SHA` is a bit faster than `Digest::SHA1`, `Digest::SHA1` has been removed from some Linux distributions, `Digest::SHA` is a core library (as of Perl >= 5.10.0) and `Digest::SHA1` is not (and never will be). See also: https://stackoverflow.com/questions/3420720/what-are-the-advantages-of-digestsha-over-digestsha1

**Comment by bigio** [comment]
Thanks,  
I switched to Digest::SHA in commit c421b20cb0fe40f22ee106ef0a25279657315a8a
