### ISSUE TITLE
2.86 Example for windows doesn't format SpamAssassinReport.txt properly

### ISSUE THREAD

**Issue by zbourdeau** [The-McGrail-Foundation/MIMEDefang#57]
During a recent refactor the $ was removed from the report in the example configuration.

action_add_part($entity, "text/plain", "-suggest",
		                "**$**report\n",
				"SpamAssassinReport.txt", "inline");

**Comment by zbourdeau** [comment]
I have a branch ready with this fix and am happy to create a PR if you grant me contributor permissions.

**Comment by bigio** [comment]
You can fork the project and create PR.
