### ISSUE TITLE
2.86 - suggested-minimum-filter-for-windows-clients example crash

### ISSUE THREAD

**Issue by zbourdeau** [The-McGrail-Foundation/MIMEDefang#59]
There appears to be a code defect in the suggested-minimum-filter-for-windows-clients / mimedefang-filter example of 2.86. with the current patches applied.

I have taken the following actions to try to remediate this issue:

1) I applied the define removal patch to correctly determine RSPAMD but that creates other process crashes.

Mar 11 02:05:59 host mimedefang-multiplexor[4341]: Worker 0 died prematurely -- check your filter rules
Mar 11 02:05:59 host mimedefang-multiplexor[4341]: Reap: worker 0 (pid 8478) exited normally with status 2 (WORKER DIED UNEXPECTEDLY)
Mar 11 02:05:59 host mimedefang-multiplexor[4341]: Worker 0 resource usage: req=1, scans=1, user=3.326, sys=0.181, nswap=0, majflt=0, minflt=26333, maxrss=106732, bi=0, bo=40

2) I reverted the change to ensure that mailflow continues. In this case I notice that X-Spam header doesn't get applied for any messages.

I haven't been able to investigate the root cause to determine the source and patch the issue so I am creating this issue to flag that this is an open issue that needs work in the event that someone else has the time to investigate this issue.

**Comment by bigio** [comment]
suggested-minimum-filter-for-windows-clients example file now has rspamd(8) code commented out, it needs a configured rspamd(8) server to work properly.
