### ISSUE TITLE
v3.0 release archive has invalid magic

### ISSUE THREAD

**Issue by a16bitsysop** [The-McGrail-Foundation/MIMEDefang#61]
If I download https://github.com/The-McGrail-Foundation/MIMEDefang/archive/v3.0.tar.gz

Unarchiving gives the error: `gzip: invalid magic` with busybox gunzip and with actual gzip `gzip: v3.0.tar.gz: not in gzip format`

**Comment by grumpybozo** [comment]
Where did you get that specific URL from? It is not behind any of the links on the releases page at https://github.com/The-McGrail-Foundation/MIMEDefang/releases

GitHub responds with an error message when I try it.   

The canonical URLs for the 3.0 release are https://github.com/The-McGrail-Foundation/MIMEDefang/releases/download/v3.0/mimedefang-3.0.tar.gz for the built package and https://github.com/The-McGrail-Foundation/MIMEDefang/archive/refs/tags/v3.0.tar.gz for the source code archive, which does not include compiled executables or prepared man pages.

**Comment by a16bitsysop** [comment]
a lot of alpine linux packages use that syntax url for github, I think there is a difference in how it is packaged.

the download url worked
