### ISSUE TITLE
Requirement for modern Perl Mail::DKIM > 1.2020

### ISSUE THREAD

**Issue by robert-scheck** [The-McGrail-Foundation/MIMEDefang#64]
Since MIMEDefang 3.0, the modern Perl `Mail::DKIM` > 1.2020 is required, which impacts especially long-term Linux distributions:

 - CentOS/RHEL 7: `Mail::DKIM` 0.39 (distribution reaches end of life at June 30, 2024)
 - CentOS/RHEL/Rocky 8: `Mail::DKIM` 0.54 (distribution reaches end of life at May 31, 2029)
 - CentOS/RHEL/Rocky 9: `Mail::DKIM` 1.20200907
 - Fedora 35: `Mail::DKIM` 1.20200907
 - Fedora 36: `Mail::DKIM` 1.20200907
 - Fedora Rawhide: `Mail::DKIM` 1.20220520

From what I can see, the `Mail::DKIM` requirement is not really conditional/optional right now, which would leave CentOS/RHEL/Rocky before version 9 on MIMEDefang 2.86 until the distribution goes end of life. If this is intended by upstream, it's fine for me, too. I just wanted to raise this.

One might argue that `Mail::DKIM` is not really required, however without `Mail::DKIM`, `make test` fails and the unconditional installation of `Mail/MIMEDefang/DKIM.pm` and `Mail/MIMEDefang/DKIM/ARC.pm` still leads to a run-time dependency generated by RPM. I did not yet test, if I just could drop these two files myself during installation (and/or if just dropping one file might be still good enough to provide the maximum functionality with the old `Mail::DKIM` versions).

P.S.: `Mail/MIMEDefang/Authres.pm` depends on `Mail::MIMEDefang::DKIM` as I noticed now, so ripping just out the `Mail::DKIM` part doesn't seem to work as mentioned above.

In the end I would like to hear your upstream opinion and/or suggestions here.

**Comment by bigio** [comment]
Mail::DKIM > 1.2020 is required only for ARC, all other code paths work with 0.54 as well.
If needed I can make tests work without Mail::DKIM as well.

**Comment by robert-scheck** [comment]
Ah! Then let me try to build it on CentOS/RHEL 7/8 without ARC…

**Comment by robert-scheck** [comment]
…okay, I've now done this: Removed `Mail/MIMEDefang/DKIM/ARC.pm` and `Mail::MIMEDefang::DKIM::ARC.3` (and `t/arc.t`) for CentOS/RHEL(/Rocky) 7 and 8. This leads to installable packages (due to no dependencies to `Mail::DKIM::ARC::Signer` etc.) and the tests succeed, too.

And for all other active versions of CentOS/RHEL/Rocky and Fedora, before mentioned files are not removed.

Given this only applies to non-latest Linux distributions, I'm not sure if these changes need to become part of upstream. For me it would be okay to have them downstream-only. If you agree, feel free to close this case simply.

**Comment by bigio** [comment]
this way on CentOS8 it will never be possible to use ARC subs even if the user installed an updated Mail::DMARC version on his own.
I will take a look if I can make ARC code compatible with older Mail::DMARC versions anyway.

**Comment by robert-scheck** [comment]
Thank you! Independent of that I've requested with https://bugzilla.redhat.com/show_bug.cgi?id=2115986 at Red Hat to rebase `Mail::DKIM` for RHEL 8 – but if that happens (or not) is indeed unclear.

Btw, once your changes show up in a new MIMEDefang release, I'll remove the dropping of `Mail/MIMEDefang/DKIM/ARC.pm` and `Mail::MIMEDefang::DKIM::ARC.3` (and `t/arc.t`) then.
