### ISSUE TITLE
Mail/MIMEDefang/Unit.pm causes run-time dependencies to Test::Class, Test::Most, Net::SMTP

### ISSUE THREAD

**Issue by robert-scheck** [The-McGrail-Foundation/MIMEDefang#65]
By default MIMEDefang 3.0 installs `Mail/MIMEDefang/Unit.pm` which makes use of `Test::Class`, `Test::Most` and `Net::SMTP`, which get picked up by RPM finally. This leads to (unnecessary?) run-time dependencies to `Test::Class`, `Test::Most`, `Net::SMTP`. Is this intended? Or should I drop `Mail/MIMEDefang/Unit.pm` on downstream-side myself simply?

**Comment by bigio** [comment]
Unit.pm can be dropped from distribution, it's needed only by regression tests.

**Comment by robert-scheck** [comment]
Thank you for the clarification, I'll then drop `Mail::MIMEDefang::Unit` (Perl module and man page) for Fedora and EPEL.
