### ISSUE TITLE
Increase SpamAssassin size threshold

### ISSUE THREAD

**Issue by blainemotsinger** [The-McGrail-Foundation/MIMEDefang#67]
For the last while, spam has been regularly getting through SpamAssassin because the message contains an attachment larger than 100kB and the message not scanned.

```
        if (-s "./INPUTMSG" < 100*1024) {
            # Only scan messages smaller than 100kB.    Larger messages
            # are extremely unlikely to be spam, and SpamAssassin is
            # dreadfully slow on very large messages.
```

Please consider raising the default size.  Spammy attachments have been up to 3MB on my server.

I understand the nature of the mimedefang-filter allows the user to modify this themselves.  But as a default it would be nice to have it a little higher.  It seems spammers are now sending messages with somewhat larger attachments to get around SpamAssassin; perhaps not a new technique, but something I've started seeing more frequently lately.

**Comment by grumpybozo** [comment]
Bumped to 512KB. Going higher risks causing severe problems on slower systems. I also weakened the comment language so as to be less emphatic.

As you note, mimedefang-filter is intended to be user-crafted, and the example in the source bundle is just that: an example.
