### ISSUE TITLE
mimedefang dies on non-ascii filenames (#54 is back)

### ISSUE THREAD

**Issue by mbouyer** [The-McGrail-Foundation/MIMEDefang#74]
Hello,
I just found mimedefang (3.3) dying trying to deal with some attachement:
For privacy I won't put the complete attachement filename here but it seems that the problematic part showed up in log as:
re%301sultats

Feb 28 20:39:47 mailhost mimedefang-multiplexor[29992]: 31SJdfJu008556: Worker 0 stderr: open body: Invalid argument at /usr/pkg/lib/perl5/vendor_perl/5
Feb 28 20:39:47 mailhost mimedefang-multiplexor[29992]: 31SJdfJu008556: Worker 0 stderr: .36.0/MIME/Entity.pm line 1897.
Feb 28 20:39:47 mailhost mimedefang-multiplexor[29992]: Worker 0 died prematurely -- check your filter rules
Feb 28 20:39:47 mailhost mimedefang[1954]: 31SJdfJu008556: Error from multiplexor: ERR No response from worker
Feb 28 20:39:47 mailhost sendmail[8556]: 31SJdfJu008556: Milter: data, reject=451 4.3.2 Please try again later

Using the same trick (in attached patch file) as commit 456aeb1 fixed it for me. But is seems that a similar code was present and removed commit 30ff081 ...

[patch-modules_lib_Mail_MIMEDefang_MIME.pm.txt](https://github.com/The-McGrail-Foundation/MIMEDefang/files/10854305/patch-modules_lib_Mail_MIMEDefang_MIME.pm.txt)

**Comment by bigio** [comment]
Could you share (privately if you prefer) the `mimedefang-filter(5)` section that triggers the issue ?

**Comment by mbouyer** [comment]
On Tue, Feb 28, 2023 at 01:13:50PM -0800, Giovanni Bechis wrote:
> Could you share (privately if you prefer) the `mimedefang-filter(5)` section that triggers the issue ?

Sure, it's very similar to the default one. It's part of "sub filter":
    if (filter_bad_filename($entity)) {
        md_graphdefang_log('bad_filename', $fname, $type);
        return action_drop_with_warning("An attachment named $fname was removed from this document as it\nconstituted a security hazard.  If you require this document, please contact\nthe sender and arrange an alternate means of receiving it.\n");
    }


-- 
Manuel Bouyer ***@***.***>
     NetBSD: 26 ans d'experience feront toujours la difference
--

**Comment by bigio** [comment]
Could you try if commit https://github.com/The-McGrail-Foundation/MIMEDefang/commit/a6470d73947198fd135d03caea7fcb03284476c9 fixes your issue ?

**Comment by mbouyer** [comment]
On Tue, Feb 28, 2023 at 02:22:25PM -0800, Giovanni Bechis wrote:
> Could you try if commit https://github.com/The-McGrail-Foundation/MIMEDefang/commit/a6470d73947198fd135d03caea7fcb03284476c9 fixes your issue ?

yes, that fixes it, thanks.
I wonder what would happen with non-UTF8, non-ascii filename though (say,
some windows or mac encoding) ?

-- 
Manuel Bouyer ***@***.***>
     NetBSD: 26 ans d'experience feront toujours la difference
--

**Comment by bigio** [comment]
Encoding changes the content of the file, not the filename afaik.
This part of the code doesn't check file contents.

**Comment by mbouyer** [comment]
On Thu, Mar 02, 2023 at 09:58:35AM -0800, Giovanni Bechis wrote:
> Encoding changes the content of the file, not the filename afaik.
> This part of the code doesn't check file contents.

the filename itself can be encoded with something else than utf-8, isn't it ?
Here I have
Content-Type: application/vnd.ms-excel.sheet.macroenabled.12;
        x-unix-mode=0644;
        name="=?utf-8?Q?re=CC=81sultats=2Exlsm?="

but we could have something else instead of ?utf-8?, isn't it ?

-- 
Manuel Bouyer ***@***.***>
     NetBSD: 26 ans d'experience feront toujours la difference
--

**Comment by bigio** [comment]
Looking at RFC 6532, it seems only utf-8 is supported.
