### ISSUE TITLE
Unable to convert text in character set `GB18030' to UTF-8

### ISSUE THREAD

**Issue by flohoff** [The-McGrail-Foundation/MIMEDefang#77]
Running git fore some days i found this:

```
Apr 11 12:17:10 svrh1smtpmx01p mimedefang-multiplexor[556979]: B903C221C11: Worker 1 stderr: Unable to convert text in character set `GB18030' to UTF-8... i
Apr 11 12:17:10 svrh1smtpmx01p mimedefang-multiplexor[556979]: B903C221C11: Worker 1 stderr: gnoring
Apr 11 12:17:10 svrh1smtpmx01p mimedefang-multiplexor[556979]: B903C221C11: Worker 1 stderr:  at /usr/share/perl5/MIME/Head.pm line 799.
Apr 11 12:17:10 svrh1smtpmx01p mimedefang-multiplexor[556979]: B903C221C11: Worker 1 stderr: Unable to convert text in character set `GB18030' to UTF-8... i
Apr 11 12:17:10 svrh1smtpmx01p mimedefang-multiplexor[556979]: B903C221C11: Worker 1 stderr: gnoring
Apr 11 12:17:10 svrh1smtpmx01p mimedefang-multiplexor[556979]: B903C221C11: Worker 1 stderr:  at /usr/share/perl5/MIME/Head.pm line 799.
Apr 11 12:17:10 svrh1smtpmx01p mimedefang-multiplexor[556979]: B903C221C11: Worker 1 stderr: Unable to convert text in character set `GB18030' to UTF-8... i
Apr 11 12:17:10 svrh1smtpmx01p mimedefang-multiplexor[556979]: B903C221C11: Worker 1 stderr: gnoring
Apr 11 12:17:10 svrh1smtpmx01p mimedefang-multiplexor[556979]: B903C221C11: Worker 1 stderr:  at /usr/share/perl5/MIME/Head.pm line 799.
```

**Comment by grumpybozo** [comment]
This is almost certainly due to missing support in your Perl installation for the GB18030 character encoding, a comprehensive encoding for Chinese characters. That support requires the Encode::HanExtra module, which you can install via CPAN.

Quoting the FreeBSD package description for Encode::HanExtra:

> Perl 5.7.3 and later ships with an adequate set of Chinese encodings,
> including the commonly used CP950, CP936 (also known as GBK), Big5
> (alias for Big5-Eten), Big5-HKSCS, EUC-CN, HZ, and ISO-IR-165.
> 
> However, the numbers of Chinese encodings are staggering, and a complete
> coverage will easily increase the size of perl distribution by several
> megabytes; hence, this CPAN module tries to provide the rest of them.
