### ISSUE TITLE
variable not available

### ISSUE THREAD

**Issue by lucize** [The-McGrail-Foundation/MIMEDefang#80]
don't know what's the real issue, I want to use fetchmail to send mails to different recipients based on attachments of the mail but only if the recipient is a desired one so it seems that I can't compare `$recipient` with a defined variable in the `sub filter_begin {}`
the `$recipient` variable is available in the `sub filter_recipient {}` and I've exported it in a global variable like 

`$global_recipient = $recipient; `

the global variable was defined at the beginning of the file

`my $global_recipient  ;`
and in 
`sub filter_begin {}` I have none of them, or this is the wrong place to do the filtering ? if I write the variable to file and load it in the filter_begin then it works but then I have to see how to keep the files unique if there are parallel processing
the mimedefang is called by postfix via socket but also tried via inet interface, version mimedefang-3.4.1-1.el9.x86_64

**Comment by bigio** [comment]
`$recipient` is available in `filter_recipient` which is called after `filter_begin`.   
In `filter_begin` or `filter_end` you could use `@Recipients` which contains all the recipients of the email.

**Comment by lucize** [comment]
something is not right on my side as I'm trying all kinds of combinations and it's not working and looking at the log output it seems on my side that the filter_recipient is called before filter_begin, MDLOG prints everything perfectly also the postfix queue ID, so I don't understand from where they are pulled as every print before and after the MDLOG printed empty variables

```
Dec  2 20:09:20 fetchmail postfix/smtpd[18974]: connect from localhost[::1]
Dec  2 20:09:20 fetchmail mimedefang.pl[18970]: function filter_recipient ---> Recipient: <need_to_process@mail.com>
Dec  2 20:09:20 fetchmail postfix/smtpd[18974]: 1540ECA8382: client=localhost[::1]
Dec  2 20:09:20 fetchmail postfix/cleanup[18979]: 1540ECA8382: info: header From: me <me@mail.com> from localhost[::1]; from=<me@mail.com> to=<need_to_process@mail.com> proto=ESMTP helo=<fetchmail>
Dec  2 20:09:20 fetchmail postfix/cleanup[18979]: 1540ECA8382: info: header To: "need_to_process@mail.com" <need_to_process@mail.com> from localhost[::1]; from=<me@mail.com> to=<need_to_process@mail.com> proto=ESMTP helo=<fetchmail>
Dec  2 20:09:20 fetchmail postfix/cleanup[18979]: 1540ECA8382: info: header Subject: FW: xml test from localhost[::1]; from=<me@mail.com> to=<need_to_process@mail.com> proto=ESMTP helo=<fetchmail>
Dec  2 20:09:20 fetchmail postfix/cleanup[18979]: 1540ECA8382: message-id=<AM6PR03MB40408184F5AB038329088F4FAE352@AM6PR03MB4040.eurprd03.prod.outlook.com>
Dec  2 20:09:20 fetchmail mimedefang.pl[18950]: 1540ECA8382: function filter_begin  ---> Processing email for recipients:
Dec  2 20:09:22 fetchmail mimedefang.pl[18950]: 1540ECA8382: MDLOG,1540ECA8382,mail_in,,,<me@mail.com>,<need_to_process@mail.com>,FW: xml test

```
in postfix I'm calling it like:
`smtpd_milters = unix:/var/spool/MIMEDefang/mimedefang.sock`

**Comment by grumpybozo** [comment]
On 2024-12-02 at 11:33:15 UTC-0500 (Mon, 02 Dec 2024 08:33:15 -0800)
Giovanni Bechis 
***@***.***>
is rumored to have said:

> `$recipient` is available in `filter_recipient` which is called after 
> `filter_begin`.

No. filter_recipient is called before filter_begin at RCPT time, once 
for each recipient. It does not have access to the message headers or 
body.

filter_begin() is called at end-of-DATA time once for each full message. 
It has access to @Recipients which has all of the recipients and it has 
the full mail headers and body.

This is documented in the mimedefang.pl(5) man page.

> In `filter_begin` or `filter_end` you could use ***@***.***` which 
> contains all the recipients of the email.
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/The-McGrail-Foundation/MIMEDefang/issues/80#issuecomment-2512066279
> You are receiving this because you are subscribed to this thread.
>
> Message ID: 
> ***@***.***>


-- 
Bill Cole
***@***.*** or ***@***.***
(AKA @***@***.*** and many ***@***.*** 
addresses)
Not Currently Available For Hire

**Comment by lucize** [comment]
in the end as I needed the filtering only for specific recipients I've done it to skip filtering like this:
don't understand why $recipients is not in the other functions, or should have used '@recipients' with @ ?


```
sub filter_recipient {
 my ($recipient) = @_;

    my $target_recipient = '<target@mail.com>';
#    md_syslog('info', "Recipient: $recipient");

    # Compare recipient with target recipient
    if ($recipient eq $target_recipient) {
        # Proceed with mail filtering
        # Add your mail filtering logic here
        md_syslog('info', "Process PDF or XML: $recipient");
        return ('CONTINUE', "ok");
    } else {
        # Exit without processing
        md_syslog('info', "Skipping milter for: $recipient");
        return ('ACCEPT_AND_NO_MORE_FILTERING', "ok");
    }
}

```
I guess CONTINUE is redundant

**Comment by bigio** [comment]
In other subs you should use `@recipients` since you  might have more recipients in the email you are processing, using `filter_recipient` is the correct way to handle the situation anyway.
