### ISSUE TITLE
mimedefang worker hang on next request after call to rspamd_check()

### ISSUE THREAD

**Issue by totaru** [The-McGrail-Foundation/MIMEDefang#81]
Symptom:
 worker process hangs on the next request after a call to rspamd_check()
 strace shows it is stuck in read() syscall.

Cause:
  rspamd_check sets $/ to undef, see there:
https://github.com/The-McGrail-Foundation/MIMEDefang/blob/bdb9761854c946b7ff163d76dab13c53c8bf3dec/modules/lib/Mail/MIMEDefang/Antispam.pm#L464

 Setting $/ to undef causes the <> operator to read till EOF. That is used in the next line, but as this is a global variable the read of the next instruction is till EOF too...

Solution:
  instead of "$/ = undef;" use "local $/;" to keep the change localized to the enclosing scope. See man perlvar at $INPUT_RECORD_SEPARATOR for reference.

This bug is present since the first implementation of rspamd http protocol in mimedefang-2.86, I'm wondering how no one else noticed.

**Comment by bigio** [comment]
Fixed, thanks.
